glyphs:
- " "
- "!"
- "\""
- "%"
- "'"
- "("
- ")"
- "*"
- "+"
- ","
- "-"
- "."
- "/"
- ":"
- ";"
- "="
- "?"
- "["
- "]"
- "^"
- "_"
- "`"
- "{"
- "}"
- "~"
- "ஂ"
- "ஃ"
- "அ"
- "ஆ"
- "இ"
- "ஈ"
- "உ"
- "ஊ"
- "எ"
- "ஏ"
- "ஐ"
- "ஒ"
- "ஓ"
- "ஔ"
- "க"
- "ங"
- "ச"
- "ஜ"
- "ஞ"
- "ட"
- "ண"
- "த"
- "ந"
- "ன"
- "ப"
- "ம"
- "ய"
- "ர"
- "ற"
- "ல"
- "ள"
- "ழ"
- "வ"
- "ஶ"
- "ஷ"
- "ஸ"
- "ஹ"
- "ா"
- "ி"
- "ீ"
- "ு"
- "ூ"
- "ெ"
- "ே"
- "ை"
- "ொ"
- "ோ"
- "ௌ"
- "்"
- "ௐ"
- "ௗ"
- "௦"
- "௧"
- "௨"
- "௩"
- "௪"
- "௫"
- "௬"
- "௭"
- "௮"
- "௯"
- "௰"
- "௱"
- "௲"
- "௳"
- "௴"
- "௵"
- "௶"
- "௷"
- "௸"
- "௹"
- "௺"
- "0"
- "1"
- "2"
- "3"
- "4"
- "5"
- "6"
- "7"
- "8"
- "9"
- "‌"
- "‍"

fonts:
- - Latha
  - [regular, bold]
- - Vijaya
  - [regular, bold]
imageHeight: 32
defaultFontSize: 11
